FROM astrocrpublic.azurecr.io/runtime:3.1-13

ENV AIRFLOW_CONN_SNOWFLAKE="snowflake://{{ SNOWFLAKE_USER }}:{{ SNOWFLAKE_PASSWORD }}@{{ SNOWFLAKE_ACCOUNT }}/{{ SNOWFLAKE_DATABASE }}/{{ SNOWFLAKE_SCHEMA }}?warehouse={{ SNOWFLAKE_WAREHOUSE }}&role={{ SNOWFLAKE_ROLE }}"